# Generated by Django 3.1.5 on 2021-05-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0003_auto_20210507_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short',
            name='day',
            field=models.DateField(),
        ),
    ]
