# Generated by Django 3.1.5 on 2021-05-13 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0005_long_notes_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='deleted_notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deleted_note_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
