# Generated by Django 3.1.5 on 2021-05-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0006_deleted_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='report_bugs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
            ],
        ),
    ]
