# Generated by Django 3.1.5 on 2021-05-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0008_user_pal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pal',
            field=models.CharField(default='blue', max_length=20),
        ),
    ]
